language: node_js
node_js:
- "6"
sudo: false
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bower cache

before_install:
- node --version
- npm config set spin false
- npm install -g npm@^3
- npm --version
- npm install -g bower
- bower --version
- npm install -g phantomjs-prebuilt
- phantomjs --version

install:
- npm install
- bower install

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
- npm test

addons:
  firefox: "latest"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

deploy:
  provider: heroku
  app:
    master: ember-api-docs-staging
    production: ember-api-docs
  api_key:
    secure: ZkKB+Ld1IokmJooZPGTZMA5L1KHBNg1qbC2KvebT9L2zTq0CEMjjzRfhmkivoG0riodz4M4rBr63UcqcnTLEoER/MU8kUt4f6gAdmi/WYCm/pxTx2vsxxwO26HFP90VDZ2yPlkYN2n+T/AYXittxRIKKBA1gxT8w9Cz4A39ojB+vpDnfhlybkes+0wpErgKgnF46eI7zz2fgbmIMqtUXgAsKey4wT4o6oqssOvEpVrtt9DX9KseDzelR6TsBafUPpYA8IMA5mqouN/HDmrY43S3a9W1SbXhvhFKads3sQO7VXIgdrbiu/clNvEaH7U9sLIW1vHnl17iQbVE2U2WibW3m6w9V/g0S96F1rDM6RZbiqgmhI5UXjVNrbmquAUE1Yxv0tVNzwq8KIZ0+4grzKwHJRDwI1Ri1J8QVBL5fQLVD669l9Hye1m6sli6VFLzGSBVYEC7fNTpk6TErgHjGsx/yThDl4QBzOitsmRzCxq3puloIUhF+aQ09T8G4OySq6wOgDwAbNFlMxDGmnglu3SXsu3xT74wOF8tLpdl4dk/DozYQQRyAFdpQHK+WHb5PswWifjEkypALCTdsZoehrzzxPPletNH9iXXMCW3c7jys5ad9RngJWy/Ka5mhk3bg5UAWvXnM3pWSGrOD2t36gq7k6FQVi7LF8BD9tD4GxxE=

env:
  global:
  - CXX=g++-4.8
  - secure: evhSAaz1oeXLAUSQtiYST86SCjyffOOF6GYbv7qRFl2LbGdQH4ViI3K+t/WkDwjY/i6AAKJ2OsF04UMT3O3bMgOVbKOOfP+KQtKa4SWn8obllMREij9cSbCxkz/pmuWUQLoVMtkT00jKRf7JJkC/x60Bn3d3g3ChAQUtOSHyKHfYjxFn1JqZygy1sSKycYMQrQ1q/tk8bCwnzh0+MFuJT62QvYd9iJ4eYfy4H8evfwsaHvOOp3fgWBF4KWRN3Wn0oeIXBWvkALRlUAJWjZKItf9zt6ReMhiEZ2gr1J5aAGp/lWk7rKnTXR31pP2AVyv2JE4olLlA6B4IXfJXR7su8nSDrznlcX+Hjf6NhAUPeNkzAf2bnsxxhlGtVuTtPZ/MUAxsa6xYtnvOooOPHSgtDJ8kPUTQ4jj9IJGg7iZhb1QpkF+YixeigITE7D9NwX5brHkdo9Eb2jUQTmo5voRswx2H4S+ZQazcQ27LNCJfKGNw6j6DA12DJTnwSzihS+4dtko3TFzEcxu9HbFU8pTfFVzhFYKWbZvNnrhkiQf/IrwMgaOgXo30tiNnPn9sTxySg+ZLvDnqNBZczeItSc0VZmFVqxJYxMKri7DUx4PmEK+P4dIeT+YJ9p5uy2VrDaSH+sXrrILt0TjotR1m6i2+sBfVITLp9ffFNzY3qA5kO3k=
  - secure: EhvzPGGvS2izYWcIwmQ7GGyc9uc7j8UQpD0/u+FqPjRBDnQ+/kg+c7w+o5l5zC6hbWXkmnPhlpGP5N+ADZ7CCmgilflZH/Or+/XAoKogkCTtQLA5o/CJ0wA6o0+jUANUDsK/zUgDbWQDSV4gyVsmxp8sPPCQtN4IsuM13cLnLaIUbQJes4XbyB5gfG0ccnftEIYmk3frFz1q8d8O0LjEU1F3tjhumSzAYxWHZwOkuSOlHkjOCYakoaZYukuXqbbREEr0UYrCkTo2Saq1O6bpfaqggTaWls5lcGc0MqG725aGTOVtFrzZPGzrfPHwQBWXb0L20gnP0k/uM1RsJsleiAU/7Fp3YaaUzjWhdB1+PhavD2jNOAA3mlxGk7r23Dhc3bkAvvsG0Odfv47h+IhuHL1OUvCMtUPtcfdizcbKTOkRh7Ow+RBmQrC7cDvOqsCuQE4ddzk3os5EypiWA1d9sDjLvjHQm34Bx7DTjUTR4F6vJP2WeYT0qsP0M6pZ7mR+EidwIC2mNH4rL1X9Fjgjgb2ltCw4MyFbcn2kQ7RZTjZK2CmwP9jydgTBjH8SEctITqwEctZcnvRp5r+DFcgykLUhHaE764xHmtnAs3RnIwuQ6rFcEvFYJpjeBBuDzEqyq66udawQ5DovJw30QTlhy4J9CtO+85V0Q5fmndCRJf4=
